@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor SCRAPER_COLOR
skinparam classBackgroundColor SCRAPER_COLOR

abstract class Command {
CommandResult execute()
}

abstract class AddCommand
class AddConsultationCommand
class AddMasteryCheckCommand
class AddTaskCommand
interface Model

Command <|-- AddCommand

AddCommand <|-- AddConsultationCommand
AddCommand <|-- AddMasteryCheckCommand
AddCommand <|-- AddTaskCommand

AddConsultationCommand ..> Model
AddMasteryCheckCommand ..> Model
AddTaskCommand ..> Model

@enduml
