@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueStudentsList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueStudentsList
UniqueTagList -[hidden]down- UniqueStudentsList

UniqueTagList *-right-> "*" Tag
UniqueStudentsList o-right-> Student

Student -up-> "*" Tag

Student *--> Name
Student *--> Telegram
Student *--> Email
Student *--> Address
@enduml
