@startuml
start
:User inputs DeleteConsultation Command;

if () then ([Index is not a non-zero unsigned integer])
    : GUI displays error message;
else ([Index is a non-zero unsigned integer])
    if () then ([Index is out of range])
        : GUI displays error message;
    else (Index is valid])
        : Consultation is removed from Jarvis;
    endif
endif
stop
@enduml
