@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class UserLogin
Class ReadOnlyUserPrefs
Class ReadOnlyUserLogin

Package Student {
Class Student
Class Email
Class Name
Class Telegram
Class UniqueStudentList
}

Package Mission {
Class Mission
Class MissionList
}

Package Quest {
Class Quest
Class QuestList
}

Package Consultation {
Class Consultation
Class ConsultationList
}

Package MasteryCheck {
Class MasteryCheck
Class MasteryCheckList
}

Package Task {
Class Task
Class Todo
Class Event
Class Deadline
Class UniqueTasksList
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager o-right-> "1" UserLogin
UserLogin .up.|> ReadOnlyUserLogin

AddressBook *--> "1" UniqueStudentList
UniqueStudentList o--> "*" Student
Student *--> Name
Student *--> Telegram
Student *--> Email

Name -[hidden]right-> Telegram

AddressBook *--> "1" UniqueTasksList
UniqueTasksList o--> "*" Task
Todo -up-|> Task
Deadline -up-|> Task
Event -up-|> Task

AddressBook *--> "1" MasteryCheckList
MasteryCheckList o--> "*" MasteryCheck

AddressBook *--> "1" ConsultationList
ConsultationList o--> "*" Consultation

AddressBook *--> "1" QuestList
QuestList o--> "*" Quest

AddressBook *--> "1" MissionList
MissionList o--> "*" Mission

@enduml
