@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor SCRAPER_COLOR
skinparam classBackgroundColor SCRAPER_COLOR

class Scraper <<Interface>>
class ReadOnlyUserLogin <<Interface>>
class UserLogin implements ReadOnlyUserLogin

package Chrome_Driver {
class WebDriver
}

class ScraperManager implements Scraper

ScraperManager o-> "1" UserLogin
ScraperManager o--> "1" WebDriver

@enduml
