@startuml
!include style.puml

participant ":ViewAllStudentsCommand" as ViewAllStudentsCommand SCRAPER_COLOR
participant ":Model" as Model SCRAPER_COLOR
participant ":CommandResult" as CommandResult SCRAPER_COLOR

[-> ViewAllStudentsCommand : execute(model)
activate ViewAllStudentsCommand

ViewAllStudentsCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_STUDENTS)

activate Model

Model -> ViewAllStudentsCommand

deactivate Model

create CommandResult

ViewAllStudentsCommand -> CommandResult : CommandResult("Listed all students taught by you")

activate CommandResult

CommandResult -> ViewAllStudentsCommand : command result

deactivate CommandResult

[<-- ViewAllStudentsCommand : command result

deactivate ViewAllStudentsCommand

@enduml